name: carrent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  onboarding: 
    path: ./packages/onboarding

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^6.1.0

flutter:
  uses-material-design: true
